TypeScript issue on display prop
mmazzarolo/react-native-modal-datetime-picker pull request #585
Opened 2021-07-22 10:16 UTC by DilipCoder

# Overview
#567 

I have made the union of both types here.
as here the community picker is being used so it will pick the platform-specific props and also fail-safe for other props.

  

# Test Plan
no functional changes here
once after build you can use the available props.

2021-07-22 12:19 UTC, mnajjarian commented
I'm not a TypeScript expert, but I guess this also would work:

`export type ReactNativeModalDateTimePickerProps = DateTimePickerProps &
  Omit<IOSNativeProps, "value" | "mode"> |
  Omit<AndroidNativeProps, "value" | "mode">;
`
So you don't need to make extra changes.
What do you think @DilipCoder?

2021-07-23 10:35 UTC, DilipCoder commented
> I'm not a TypeScript expert, but I guess this also would work:
> 
> `export type ReactNativeModalDateTimePickerProps = DateTimePickerProps & Omit<IOSNativeProps, "value" | "mode"> | Omit<AndroidNativeProps, "value" | "mode">; `
> 
> So you don't need to make extra changes.
> What do you think @DilipCoder?

it will do the union for all the props.  pushing the pr again

2021-07-24 12:52 UTC, mmazzarolo approved these changes
LGTM. I assume this is a breaking change, right? Not in the sense of introducing breaking changes at runtime, but it *may not* be retro-compatible and break type checks.

2021-07-24 12:53 UTC, mmazzarolo commented
Also, thank you @DilipCoder and @mnajjarian :)

2021-07-25 22:55 UTC, DilipCoder commented
> I'm not a TypeScript expert, but I guess this also would work:
> 
> `export type ReactNativeModalDateTimePickerProps = DateTimePickerProps & Omit<IOSNativeProps, "value" | "mode"> | Omit<AndroidNativeProps, "value" | "mode">; `
> 
> So you don't need to make extra changes.
> What do you think @DilipCoder?

2021-07-25 23:00 UTC, DilipCoder commented
@mmazzarolo  can you help me to build this package locally. I want to check before it will be merged.

2021-07-26 07:37 UTC, mmazzarolo commented
@DilipCoder there's no build step in the package. If you want to test your types, you can install the library version of this PR with something like `yarn add mmazzarolo/react-native-modal-datetime-picker#585/head` 👍 Let me know how It goes.

2021-08-14 09:28 UTC, mmazzarolo requested changes
Had some time to give it a try. There are a few things that I think we should change (just removing a few definitions) but overall looks good 👍 

The way I tested it is with the following very manual (but simple) process:

1. Create a new expo project: `expo init picker-example && cd picker-example`.
2. Install `react-native-modal-datetime-picker`: `expo install react-native-modal-datetime-picker @react-native-community/datetimepicker`.
3. Update `App.tsx` to show the picker (you can use the example from the README.md.
4. Update `picker-example/node_modules/react-native-modal-datetime-picker/typings/index.d.ts` with the changes of this PR. 
5. Play with the `display` prop in `App.tsx` and check the type errors 👍

2021-08-14 09:28 UTC, mmazzarolo commented on typings/index.d.ts
> +  mode?: 'date' | 'time' | 'datetime' | 'countdown';
We're not supporting `countdown`, could you revert this line change?

2021-08-14 09:28 UTC, mmazzarolo commented on typings/index.d.ts
> +   display?: Display | IOSDisplay
Can we remove the `display` definition here? It should be inferred from the changes below 👍

2021-08-14 09:28 UTC, mmazzarolo commented on typings/index.d.ts
> +  Omit<IOSNativeProps, "value" | "mode"> |
This seems to work 👍 
Just to make it clearer, can we split this definition in two statements?
```js
type NativePickerProps = Omit<IOSNativeProps, "value" | "mode"> | Omit<AndroidNativeProps, "value" | "mode">

export type ReactNativeModalDateTimePickerProps = DateTimePickerProps & NativePickerProps;
```

2021-09-22 10:15 UTC, exneval commented
Hi, thanks for the great work, just checking up, any ETA of this PR can be merged?

2021-09-22 11:34 UTC, mmazzarolo commented
@exneval it's blocked because of the issues above ☝️ feel free to jump in if you wanna contribute 👍

2022-02-28 10:14 UTC, HarvWorks commented
@mmazzarolo How can I help?  Can I just create a new fork to make a new PR or do I have to use @DilipCoder's fork?

2022-02-28 10:16 UTC, mmazzarolo commented
@HarvWorks I'm fine with both options, thanks!

2022-03-30 11:36 UTC, mmazzarolo commented
Closed #636

2022-03-30 11:36 UTC, closed without merging