removeListener deprecated in favor of remove()
mmazzarolo/react-native-modal-datetime-picker pull request #591
Opened 2021-08-19 13:36 UTC by rodrigofeijao

# Overview

With ReactNative 0.65.0 the removeListener was deprecated in favor of `remove()`

https://github.com/react-native-community/releases/blob/master/CHANGELOG.md#deprecated

2021-08-21 12:10 UTC, mmazzarolo requested changes
👋 @rodrigofeijao PR is looking good, thanks! 
May I ask you to set `"react-native": ">=0.65.0"` as a `peerDependency` in `package.json`? 
This is a breaking change and we should ensure to mark it as compatible with 0.65 onwards only.

2021-08-23 03:09 UTC, teckbeng-payboy commented
Roughly when this PR will be up to production?

2021-08-23 07:22 UTC, rodrigofeijao commented
@mmazzarolo Thanks for reviewing it. I've just added the requested change. If there's anything else you think we need to change, please let me know.

2021-08-23 07:47 UTC, mmazzarolo commented
Thank you! The code is looking good — I can't test it for a couple of days though. 
Is anyone willing to give it a try/double-check to speed up the merging of the PR??

2021-09-01 07:25 UTC, merged